# Generated by Django 6.0.3 on 2026-03-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ebooks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('uread', models.IntegerField()),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebooks.ebook')),
            ],
            options={
                'unique_together': {('ebook', 'month')},
            },
        ),
    ]
