# Generated by Django 6.0.3 on 2026-03-13 15:22

import django.core.validators
import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('COMP', 'คอมพิวเตอร์'), ('DATA', 'วิทยาศาสตร์ข้อมูล'), ('CENG', 'วิศวกรรมคอมพิวเตอร์')], max_length=4)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover', models.ImageField(upload_to='cover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png'])])),
                ('sample', models.FileField(upload_to='sample/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('token', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('publish_date', models.DateField()),
                ('page_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('post_status', models.CharField(choices=[('P', 'Publish'), ('U', 'Unpublish')], max_length=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='LogRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebooks.ebook')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
